//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acomodacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acomodacao()
        {
            this.acomodacao_foto = new HashSet<acomodacao_foto>();
            this.acomodacao_quarto = new HashSet<acomodacao_quarto>();
            this.acomodacao_servico = new HashSet<acomodacao_servico>();
            this.carrinho_compra = new HashSet<carrinho_compra>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public string endereco { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string descricao { get; set; }
        public string foto_capa { get; set; }
        public string website { get; set; }
        public string mapa { get; set; }
        public Nullable<int> id_acomodacao_tipo { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public Nullable<bool> Inactivo { get; set; }
        public Nullable<long> id_provedor { get; set; }
    
        public virtual acomodacao_tipo acomodacao_tipo { get; set; }
        public virtual distrito distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acomodacao_foto> acomodacao_foto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acomodacao_quarto> acomodacao_quarto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acomodacao_servico> acomodacao_servico { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrinho_compra> carrinho_compra { get; set; }
    }
}
