//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class artista_obra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public artista_obra()
        {
            this.musica_album = new HashSet<musica_album>();
            this.musicas = new HashSet<musica>();
            this.obra_arte = new HashSet<obra_arte>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string fotografia { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public string telefone { get; set; }
        public Nullable<bool> e_musico { get; set; }
        public Nullable<long> id_provedor { get; set; }
    
        public virtual distrito distrito { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<musica_album> musica_album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<musica> musicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<obra_arte> obra_arte { get; set; }
    }
}
