//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class artigo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public artigo()
        {
            this.artigo_imagem = new HashSet<artigo_imagem>();
            this.carrinho_compra = new HashSet<carrinho_compra>();
        }
    
        public long id { get; set; }
        public string codigo { get; set; }
        public Nullable<int> id_categoria_artigo { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public Nullable<bool> marca_registada { get; set; }
        public Nullable<bool> atracao_internacional { get; set; }
        public Nullable<decimal> preco_min { get; set; }
        public Nullable<decimal> preco_max { get; set; }
        public Nullable<decimal> preco_venda { get; set; }
        public string observacoes { get; set; }
        public string portofolio { get; set; }
        public string genero { get; set; }
        public Nullable<bool> e_servico { get; set; }
        public string foto_capa { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public string bairro { get; set; }
        public Nullable<long> clicks { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<bool> Inactivo { get; set; }
        public Nullable<long> id_provedorr { get; set; }
        public Nullable<decimal> peso { get; set; }
    
        public virtual distrito distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<artigo_imagem> artigo_imagem { get; set; }
        public virtual categoria_artigo categoria_artigo { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrinho_compra> carrinho_compra { get; set; }
    }
}
