//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrinho_compra
    {
        public long id { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<bool> e_restaurante { get; set; }
        public Nullable<bool> e_artigo { get; set; }
        public Nullable<bool> e_acomodacao { get; set; }
        public Nullable<bool> e_taxi { get; set; }
        public Nullable<long> id_restaurante { get; set; }
        public Nullable<long> id_acomodacao { get; set; }
        public Nullable<long> id_quarto { get; set; }
        public Nullable<long> id_artigo { get; set; }
        public Nullable<long> id_taxi { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public string descricao { get; set; }
        public Nullable<bool> e_obra { get; set; }
        public Nullable<long> id_obra { get; set; }
        public Nullable<bool> e_musica { get; set; }
        public Nullable<long> id_musica { get; set; }
        public Nullable<bool> e_loja_produto { get; set; }
        public Nullable<long> id_loja_produto { get; set; }
        public Nullable<bool> e_farmacia_produto { get; set; }
        public Nullable<long> id_farmacia_produto { get; set; }
        public Nullable<bool> e_Filme { get; set; }
        public Nullable<long> id_filme { get; set; }
        public Nullable<bool> e_evento { get; set; }
        public Nullable<long> id_evento { get; set; }
    
        public virtual acomodacao acomodacao { get; set; }
        public virtual acomodacao_quarto acomodacao_quarto { get; set; }
        public virtual artigo artigo { get; set; }
        public virtual evento evento { get; set; }
        public virtual farmacia_produto farmacia_produto { get; set; }
        public virtual filme filme { get; set; }
        public virtual loja_produto loja_produto { get; set; }
        public virtual musica musica { get; set; }
        public virtual obra_arte obra_arte { get; set; }
        public virtual restaurante restaurante { get; set; }
        public virtual taxi taxi { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
