//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cinema_sessao
    {
        public long id { get; set; }
        public Nullable<long> id_cinema { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string hora { get; set; }
        public string descricao { get; set; }
        public Nullable<long> id_filme { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public Nullable<decimal> preco { get; set; }
    
        public virtual cinema cinema { get; set; }
        public virtual filme filme { get; set; }
    }
}
