//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cinema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cinema()
        {
            this.cinema_sessao = new HashSet<cinema_sessao>();
        }
    
        public long id { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public string nome { get; set; }
        public string localizacao { get; set; }
        public string descricao { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public string foto_capa { get; set; }
    
        public virtual distrito distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cinema_sessao> cinema_sessao { get; set; }
    }
}
