//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinica
    {
        public long id { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public string descricao { get; set; }
        public string nome { get; set; }
        public string bairro { get; set; }
        public string telefone { get; set; }
        public string foto_capa { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<long> id_provedor { get; set; }
        public Nullable<decimal> preco_consulta { get; set; }
    
        public virtual distrito distrito { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
