//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        public long id_compra { get; set; }
        public long id_usuario { get; set; }
        public string oque_e { get; set; }
        public Nullable<long> id_produto { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public string descricao { get; set; }
        public Nullable<bool> confirmado { get; set; }
        public string modo_pagamento { get; set; }
        public Nullable<bool> tem_entrega { get; set; }
        public Nullable<decimal> custo_transporte { get; set; }
        public Nullable<int> id_transportadora { get; set; }
        public string local_entrega { get; set; }
        public string contacto_destinatario { get; set; }
        public string nome_destinatario { get; set; }
        public string local_levantamento { get; set; }
        public Nullable<bool> sensivel { get; set; }
        public Nullable<bool> peso_grande { get; set; }
        public Nullable<bool> provedor_pago { get; set; }
        public Nullable<System.DateTime> data_provedor_pago { get; set; }
        public Nullable<decimal> total_provedor_pago { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual transportadora transportadora { get; set; }
    }
}
