//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class distrito_classificacao
    {
        public long id { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<bool> e_like { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<bool> activo { get; set; }
        public string nomeUsuario { get; set; }
        public string email { get; set; }
        public string assunto { get; set; }
        public Nullable<int> estrelas { get; set; }
    
        public virtual distrito distrito { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
