//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public string telefone { get; set; }
        public string website { get; set; }
        public string email { get; set; }
        public string endereco { get; set; }
        public string seguranca { get; set; }
        public string como_pagar { get; set; }
    }
}
