//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entidade_cultural
    {
        public long id { get; set; }
        public Nullable<int> id_categoria_cultura { get; set; }
        public string nome { get; set; }
        public string origem { get; set; }
        public string praticantes { get; set; }
        public string publico { get; set; }
        public string modalidade { get; set; }
        public string conhecidaanivel { get; set; }
        public string impacto { get; set; }
        public string publicado { get; set; }
    
        public virtual categoria_cultura categoria_cultura { get; set; }
    }
}
