//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evento()
        {
            this.carrinho_compra = new HashSet<carrinho_compra>();
            this.evento_comentario = new HashSet<evento_comentario>();
            this.evento_bilhete = new HashSet<evento_bilhete>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<System.DateTime> data_evento { get; set; }
        public string descricao { get; set; }
        public string foto_capa { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public string local { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public Nullable<bool> adiado { get; set; }
        public Nullable<bool> realizado { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<decimal> preco_bilhete { get; set; }
        public Nullable<decimal> preco_bilhete_vip { get; set; }
        public string orador { get; set; }
        public string moderador { get; set; }
        public string part_assistente { get; set; }
        public Nullable<int> nr_participantes { get; set; }
        public Nullable<long> id_provedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrinho_compra> carrinho_compra { get; set; }
        public virtual distrito distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_comentario> evento_comentario { get; set; }
        public virtual evento_categoria evento_categoria { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_bilhete> evento_bilhete { get; set; }
    }
}
