//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento_bilhete
    {
        public long id { get; set; }
        public Nullable<long> id_evento { get; set; }
        public Nullable<System.DateTime> data_compra { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<bool> vip { get; set; }
        public Nullable<long> usuario { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public string token { get; set; }
    
        public virtual evento evento { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
