//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class filme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public filme()
        {
            this.carrinho_compra = new HashSet<carrinho_compra>();
            this.cinema_sessao = new HashSet<cinema_sessao>();
            this.item_filme_categoria = new HashSet<item_filme_categoria>();
        }
    
        public long id { get; set; }
        public string minutos { get; set; }
        public string direcao { get; set; }
        public string elenco { get; set; }
        public string nacionalidade { get; set; }
        public string titulo_original { get; set; }
        public string distribuidor { get; set; }
        public Nullable<int> ano_producao { get; set; }
        public string tipo_filme { get; set; }
        public Nullable<decimal> orcamento { get; set; }
        public string idioma { get; set; }
        public string cor { get; set; }
        public string sinopse { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public string foto_capa { get; set; }
        public Nullable<decimal> preco { get; set; }
        public string link_trailer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrinho_compra> carrinho_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cinema_sessao> cinema_sessao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_filme_categoria> item_filme_categoria { get; set; }
    }
}
