//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_filme_categoria
    {
        public long id { get; set; }
        public Nullable<long> id_filme { get; set; }
        public Nullable<long> id_categoria { get; set; }
        public Nullable<bool> inactivo { get; set; }
    
        public virtual filme filme { get; set; }
        public virtual filme_categoria filme_categoria { get; set; }
    }
}
