//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loja()
        {
            this.loja_produto = new HashSet<loja_produto>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public string bairro { get; set; }
        public string descricao { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public string foto_capa { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public Nullable<int> id_tipo_loja { get; set; }
        public Nullable<long> id_provedor { get; set; }
    
        public virtual distrito distrito { get; set; }
        public virtual loja_tipo loja_tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loja_produto> loja_produto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
