//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mussika_bdEntities : DbContext
    {
        public mussika_bdEntities()
            : base("name=mussika_bdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acomodacao> acomodacaos { get; set; }
        public virtual DbSet<acomodacao_classificacao> acomodacao_classificacao { get; set; }
        public virtual DbSet<acomodacao_comentario> acomodacao_comentario { get; set; }
        public virtual DbSet<acomodacao_disponibilidade> acomodacao_disponibilidade { get; set; }
        public virtual DbSet<acomodacao_foto> acomodacao_foto { get; set; }
        public virtual DbSet<acomodacao_quarto> acomodacao_quarto { get; set; }
        public virtual DbSet<acomodacao_reserva> acomodacao_reserva { get; set; }
        public virtual DbSet<acomodacao_servico> acomodacao_servico { get; set; }
        public virtual DbSet<acomodacao_tipo> acomodacao_tipo { get; set; }
        public virtual DbSet<artigo> artigoes { get; set; }
        public virtual DbSet<artigo_imagem> artigo_imagem { get; set; }
        public virtual DbSet<artista_obra> artista_obra { get; set; }
        public virtual DbSet<carrinho_compra> carrinho_compra { get; set; }
        public virtual DbSet<categoria_artigo> categoria_artigo { get; set; }
        public virtual DbSet<categoria_cultura> categoria_cultura { get; set; }
        public virtual DbSet<categoria_obra_arte> categoria_obra_arte { get; set; }
        public virtual DbSet<cinema> cinemas { get; set; }
        public virtual DbSet<cinema_sessao> cinema_sessao { get; set; }
        public virtual DbSet<clinica> clinicas { get; set; }
        public virtual DbSet<compra> compras { get; set; }
        public virtual DbSet<distrito> distritoes { get; set; }
        public virtual DbSet<distrito_classificacao> distrito_classificacao { get; set; }
        public virtual DbSet<distrito_comentario> distrito_comentario { get; set; }
        public virtual DbSet<distrito_foto> distrito_foto { get; set; }
        public virtual DbSet<empresa> empresas { get; set; }
        public virtual DbSet<entidade_cultural> entidade_cultural { get; set; }
        public virtual DbSet<evento> eventoes { get; set; }
        public virtual DbSet<evento_categoria> evento_categoria { get; set; }
        public virtual DbSet<evento_comentario> evento_comentario { get; set; }
        public virtual DbSet<farmacia> farmacias { get; set; }
        public virtual DbSet<farmacia_produto> farmacia_produto { get; set; }
        public virtual DbSet<filme> filmes { get; set; }
        public virtual DbSet<filme_categoria> filme_categoria { get; set; }
        public virtual DbSet<genero_musical> genero_musical { get; set; }
        public virtual DbSet<hospital> hospitals { get; set; }
        public virtual DbSet<item_filme_categoria> item_filme_categoria { get; set; }
        public virtual DbSet<item_pacote_subscricao> item_pacote_subscricao { get; set; }
        public virtual DbSet<loja> lojas { get; set; }
        public virtual DbSet<loja_produto> loja_produto { get; set; }
        public virtual DbSet<loja_tipo> loja_tipo { get; set; }
        public virtual DbSet<musica> musicas { get; set; }
        public virtual DbSet<musica_album> musica_album { get; set; }
        public virtual DbSet<obra_arte> obra_arte { get; set; }
        public virtual DbSet<obra_arte_imagem> obra_arte_imagem { get; set; }
        public virtual DbSet<pacote_subscricao> pacote_subscricao { get; set; }
        public virtual DbSet<produto> produtoes { get; set; }
        public virtual DbSet<produto_categoria> produto_categoria { get; set; }
        public virtual DbSet<restaurante> restaurantes { get; set; }
        public virtual DbSet<restaurante_classificacao> restaurante_classificacao { get; set; }
        public virtual DbSet<restaurante_comentario> restaurante_comentario { get; set; }
        public virtual DbSet<restaurante_foto> restaurante_foto { get; set; }
        public virtual DbSet<restaurante_prato> restaurante_prato { get; set; }
        public virtual DbSet<restaurante_prato_categoria> restaurante_prato_categoria { get; set; }
        public virtual DbSet<restaurante_tipo> restaurante_tipo { get; set; }
        public virtual DbSet<servico> servicoes { get; set; }
        public virtual DbSet<servico_categoria> servico_categoria { get; set; }
        public virtual DbSet<servico_foto> servico_foto { get; set; }
        public virtual DbSet<taxi> taxis { get; set; }
        public virtual DbSet<taxi_categoria> taxi_categoria { get; set; }
        public virtual DbSet<tipo_produto> tipo_produto { get; set; }
        public virtual DbSet<turismo> turismoes { get; set; }
        public virtual DbSet<turismo_categoria> turismo_categoria { get; set; }
        public virtual DbSet<turismo_comentario> turismo_comentario { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<usuario_favorito> usuario_favorito { get; set; }
        public virtual DbSet<usuario_provedor> usuario_provedor { get; set; }
        public virtual DbSet<usuario_tipo> usuario_tipo { get; set; }
        public virtual DbSet<UsuarioAutenticacao> UsuarioAutenticacaos { get; set; }
        public virtual DbSet<UsuarioSessao> UsuarioSessaos { get; set; }
        public virtual DbSet<saude_reserva> saude_reserva { get; set; }
        public virtual DbSet<evento_bilhete> evento_bilhete { get; set; }
        public virtual DbSet<pagamento_subscricao> pagamento_subscricao { get; set; }
        public virtual DbSet<transportadora> transportadoras { get; set; }
        public virtual DbSet<transportadora_parametro> transportadora_parametro { get; set; }
        public virtual DbSet<transportadora_tipo_carga> transportadora_tipo_carga { get; set; }
    }
}
