//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class musica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public musica()
        {
            this.carrinho_compra = new HashSet<carrinho_compra>();
        }
    
        public long id { get; set; }
        public Nullable<int> id_genero_musical { get; set; }
        public string titulo { get; set; }
        public string artista { get; set; }
        public Nullable<int> ano { get; set; }
        public string album { get; set; }
        public string formato { get; set; }
        public string produtor { get; set; }
        public string gravadora { get; set; }
        public string link { get; set; }
        public string caminho_ficheiro { get; set; }
        public string caminho_capa1 { get; set; }
        public string caminho_capa2 { get; set; }
        public Nullable<decimal> preco_video { get; set; }
        public Nullable<decimal> preco_venda { get; set; }
        public Nullable<bool> gratis { get; set; }
        public string duracao { get; set; }
        public Nullable<bool> pode_baixar { get; set; }
        public Nullable<bool> e_album { get; set; }
        public Nullable<long> id_album { get; set; }
        public Nullable<long> id_artista_obra { get; set; }
        public Nullable<long> id_provedor { get; set; }
        public Nullable<bool> inactiva { get; set; }
    
        public virtual artista_obra artista_obra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrinho_compra> carrinho_compra { get; set; }
        public virtual genero_musical genero_musical { get; set; }
        public virtual musica_album musica_album { get; set; }
    }
}
