//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class musica_album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public musica_album()
        {
            this.musicas = new HashSet<musica>();
        }
    
        public long id { get; set; }
        public Nullable<long> id_artista { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<int> id_genero { get; set; }
        public Nullable<int> ano_lancamento { get; set; }
        public string produtor { get; set; }
        public string gravadora { get; set; }
        public Nullable<decimal> preco { get; set; }
        public Nullable<int> quantidade_musicas { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public Nullable<long> id_provedor { get; set; }
        public string foto_capa { get; set; }
    
        public virtual artista_obra artista_obra { get; set; }
        public virtual genero_musical genero_musical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<musica> musicas { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
