//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class obra_arte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public obra_arte()
        {
            this.carrinho_compra = new HashSet<carrinho_compra>();
            this.obra_arte_imagem = new HashSet<obra_arte_imagem>();
        }
    
        public long id { get; set; }
        public Nullable<int> id_categoria_obra { get; set; }
        public string titulo { get; set; }
        public string autor { get; set; }
        public string materia { get; set; }
        public string suporte { get; set; }
        public string tecnica { get; set; }
        public string dimensoes { get; set; }
        public string autoria_producao { get; set; }
        public string informacao_tecnica { get; set; }
        public string fotografo { get; set; }
        public string proprietario { get; set; }
        public string caminho_imagem { get; set; }
        public Nullable<long> id_artista_obra { get; set; }
        public Nullable<long> id_provedor { get; set; }
        public Nullable<decimal> preco_venda { get; set; }
        public string caminho_pdf { get; set; }
        public string ano { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public Nullable<decimal> peso { get; set; }
    
        public virtual artista_obra artista_obra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrinho_compra> carrinho_compra { get; set; }
        public virtual categoria_obra_arte categoria_obra_arte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<obra_arte_imagem> obra_arte_imagem { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
