//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public restaurante()
        {
            this.carrinho_compra = new HashSet<carrinho_compra>();
            this.restaurante_classificacao = new HashSet<restaurante_classificacao>();
            this.restaurante_comentario = new HashSet<restaurante_comentario>();
            this.restaurante_foto = new HashSet<restaurante_foto>();
            this.restaurante_prato = new HashSet<restaurante_prato>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public string endereco { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string descricao { get; set; }
        public string foto_capa { get; set; }
        public string website { get; set; }
        public string mapa { get; set; }
        public Nullable<int> id_restaurante_tipo { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<long> id_provedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrinho_compra> carrinho_compra { get; set; }
        public virtual distrito distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<restaurante_classificacao> restaurante_classificacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<restaurante_comentario> restaurante_comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<restaurante_foto> restaurante_foto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<restaurante_prato> restaurante_prato { get; set; }
        public virtual restaurante_tipo restaurante_tipo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
