//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurante_prato
    {
        public long id { get; set; }
        public Nullable<long> id_resturante { get; set; }
        public string nome { get; set; }
        public Nullable<decimal> preco_venda { get; set; }
        public string foto_capa { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> data_cadastrro { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public Nullable<long> id__prato_categoria { get; set; }
        public Nullable<decimal> peso { get; set; }
    
        public virtual restaurante restaurante { get; set; }
        public virtual restaurante_prato_categoria restaurante_prato_categoria { get; set; }
    }
}
