//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurante_classificacao
    {
        public long id { get; set; }
        public Nullable<long> id_restaurante { get; set; }
        public Nullable<int> classificacao { get; set; }
        public string usuario_nome { get; set; }
        public string usuario_email { get; set; }
        public string usuario_assunto { get; set; }
        public string comentario { get; set; }
        public string foto { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<long> id_usuario { get; set; }
    
        public virtual restaurante restaurante { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
