//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saude_reserva
    {
        public long id { get; set; }
        public Nullable<bool> clinica { get; set; }
        public Nullable<bool> hospital { get; set; }
        public string data_consulta { get; set; }
        public string hora_consulta { get; set; }
        public string data_cadastro { get; set; }
        public string nome_paciente { get; set; }
        public string endereco_paciente { get; set; }
        public Nullable<int> idade { get; set; }
        public string sintomas { get; set; }
        public Nullable<long> id_centro_saude { get; set; }
        public Nullable<bool> confirmado { get; set; }
        public Nullable<long> id_usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
