//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servico_foto
    {
        public int id { get; set; }
        public string caminho { get; set; }
        public Nullable<long> id_servico { get; set; }
    
        public virtual servico servico { get; set; }
    }
}
