//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transportadora_parametro
    {
        public long id_parametro_transportadora { get; set; }
        public Nullable<int> id_transportadora { get; set; }
        public Nullable<int> id_tipo_carga { get; set; }
        public Nullable<decimal> distancia_minima { get; set; }
        public Nullable<decimal> distancia_maxima { get; set; }
        public Nullable<bool> sensivel { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<int> peso_pequeno { get; set; }
        public Nullable<int> peso_medio { get; set; }
        public Nullable<int> peso_grande { get; set; }
        public Nullable<int> percentagem_sensivel { get; set; }
        public Nullable<decimal> peso_max_carga_pequena { get; set; }
        public Nullable<decimal> peso_max_carga_media { get; set; }
        public Nullable<decimal> peso_max_carga_grande { get; set; }
    
        public virtual transportadora transportadora { get; set; }
        public virtual transportadora_tipo_carga transportadora_tipo_carga { get; set; }
    }
}
