//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turismo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public turismo()
        {
            this.turismo_comentario = new HashSet<turismo_comentario>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public string localizacao { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public string foto_capa { get; set; }
        public string descricao { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<long> id_provedor { get; set; }
    
        public virtual distrito distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turismo_comentario> turismo_comentario { get; set; }
        public virtual turismo_categoria turismo_categoria { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
