//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_favorito
    {
        public long id { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<bool> e_distrito { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public Nullable<bool> e_restaurante { get; set; }
        public Nullable<long> id_restaurante { get; set; }
        public Nullable<bool> e_acomodacao { get; set; }
        public Nullable<long> id_acomodacao { get; set; }
        public Nullable<bool> e_servico { get; set; }
        public Nullable<long> id_servico { get; set; }
        public Nullable<bool> e_artigo { get; set; }
        public Nullable<long> id_artigo { get; set; }
        public Nullable<bool> e_musica { get; set; }
        public Nullable<long> id_musica { get; set; }
        public Nullable<bool> e_obra_arte { get; set; }
        public Nullable<long> id_obra_arte { get; set; }
        public Nullable<bool> e_taxi { get; set; }
        public Nullable<long> id_taxi { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
