//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.acomodacaos = new HashSet<acomodacao>();
            this.acomodacao_classificacao = new HashSet<acomodacao_classificacao>();
            this.acomodacao_comentario = new HashSet<acomodacao_comentario>();
            this.artigoes = new HashSet<artigo>();
            this.artista_obra = new HashSet<artista_obra>();
            this.carrinho_compra = new HashSet<carrinho_compra>();
            this.clinicas = new HashSet<clinica>();
            this.compras = new HashSet<compra>();
            this.distrito_classificacao = new HashSet<distrito_classificacao>();
            this.distrito_comentario = new HashSet<distrito_comentario>();
            this.eventoes = new HashSet<evento>();
            this.evento_comentario = new HashSet<evento_comentario>();
            this.farmacias = new HashSet<farmacia>();
            this.hospitals = new HashSet<hospital>();
            this.lojas = new HashSet<loja>();
            this.musica_album = new HashSet<musica_album>();
            this.obra_arte = new HashSet<obra_arte>();
            this.restaurantes = new HashSet<restaurante>();
            this.restaurante_classificacao = new HashSet<restaurante_classificacao>();
            this.restaurante_comentario = new HashSet<restaurante_comentario>();
            this.turismoes = new HashSet<turismo>();
            this.turismo_comentario = new HashSet<turismo_comentario>();
            this.UsuarioAutenticacaos = new HashSet<UsuarioAutenticacao>();
            this.usuario_favorito = new HashSet<usuario_favorito>();
            this.usuario_provedor = new HashSet<usuario_provedor>();
            this.UsuarioSessaos = new HashSet<UsuarioSessao>();
            this.evento_bilhete = new HashSet<evento_bilhete>();
            this.saude_reserva = new HashSet<saude_reserva>();
            this.pagamento_subscricao = new HashSet<pagamento_subscricao>();
            this.transportadoras = new HashSet<transportadora>();
        }
    
        public long idusario { get; set; }
        public string nome { get; set; }
        public string usuario1 { get; set; }
        public string senha { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> datacadastro { get; set; }
        public string cod_autenticao { get; set; }
        public Nullable<bool> autenticado { get; set; }
        public string msg_autenticacao { get; set; }
        public Nullable<int> id_usuario_tipo { get; set; }
        public string telefone { get; set; }
        public string tele { get; set; }
        public string foto_capa { get; set; }
        public Nullable<bool> e_provedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acomodacao> acomodacaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acomodacao_classificacao> acomodacao_classificacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acomodacao_comentario> acomodacao_comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<artigo> artigoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<artista_obra> artista_obra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrinho_compra> carrinho_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clinica> clinicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra> compras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<distrito_classificacao> distrito_classificacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<distrito_comentario> distrito_comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento> eventoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_comentario> evento_comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<farmacia> farmacias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hospital> hospitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loja> lojas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<musica_album> musica_album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<obra_arte> obra_arte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<restaurante> restaurantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<restaurante_classificacao> restaurante_classificacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<restaurante_comentario> restaurante_comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turismo> turismoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turismo_comentario> turismo_comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioAutenticacao> UsuarioAutenticacaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_favorito> usuario_favorito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_provedor> usuario_provedor { get; set; }
        public virtual Usuario Usuario11 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual usuario_tipo usuario_tipo { get; set; }
        public virtual Usuario Usuario12 { get; set; }
        public virtual Usuario Usuario3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioSessao> UsuarioSessaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_bilhete> evento_bilhete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saude_reserva> saude_reserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagamento_subscricao> pagamento_subscricao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transportadora> transportadoras { get; set; }
    }
}
