//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_provedor
    {
        public long id { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<bool> musica { get; set; }
        public Nullable<bool> bazar { get; set; }
        public Nullable<bool> loja { get; set; }
        public Nullable<bool> acomodacao { get; set; }
        public Nullable<bool> taxi { get; set; }
        public Nullable<bool> restaurante { get; set; }
        public Nullable<bool> arte_cultura { get; set; }
        public Nullable<bool> evento { get; set; }
        public Nullable<bool> turismo { get; set; }
        public Nullable<bool> farmacia { get; set; }
        public Nullable<bool> clinica { get; set; }
        public Nullable<bool> pagamento_servico { get; set; }
        public string referencia { get; set; }
        public Nullable<bool> transportadora { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
