//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Mussika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioAutenticacao
    {
        public long idAutenticacao { get; set; }
        public Nullable<long> idUsuario { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<bool> viaemail { get; set; }
        public Nullable<bool> viacell { get; set; }
        public string codigo { get; set; }
        public string resultado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
